const data = [
    {
        "maximumdrawndown": 0,
        "qtdloss": 0,
        "loss": 0,
        "payoff": 37.68,
        "gain": 37.68,
        "nickname": "pedro",
        "total": 39,
        "profitporcentagem": "132.78",
        "dadosanalisados": 5063,
        "qtdgain": 39,
        "qtddiasgain": 1166,
        "qtddiasloss": 0,
        "id": "7Td7e4XwCRGP3SmjbMsB",
        "src": "BOV_VALE3.png",
        "name": "VALE3",
        "gainporcentagem": "100.00",
        "lossporcentagem": "0.00",
        "profit": 2330,
        "score": "77.22",
        "condicao": "SINAL DE COMPRA:Bollinger=>Preço cruza para baixo da lowerband:desvio=2,periodo=20   SINAL DE VENDA:Saída=>Saida após primeiro candle no lucro:   "
    },
    {
        "qtdloss": 96,
        "nickname": "dani",
        "qtddiasgain": 3215,
        "payoff": 1.08,
        "profitporcentagem": "523.18",
        "dadosanalisados": 5063,
        "loss": -43.84,
        "gain": 47.18,
        "qtdgain": 101,
        "maximumdrawndown": -54.53,
        "qtddiasloss": 3230,
        "total": 197,
        "id": "C1l667q8aMm54GSne9hs",
        "src": "BOV_CSNA3.png",
        "name": "CSNA3",
        "gainporcentagem": "51.27",
        "lossporcentagem": "48.73",
        "profit": 6230,
        "score": "47.70",
        "condicao": "SINAL DE COMPRA:Data=>A partir dessa Data:   SINAL DE VENDA:Data=>Antes dessa Data:   "
    },
    {
        "qtddiasloss": 81,
        "payoff": 3.48,
        "maximumdrawndown": -25.78,
        "qtdgain": 27,
        "qtdloss": 30,
        "loss": -3.55,
        "nickname": "pedro",
        "profitporcentagem": "106.04",
        "gain": 12.36,
        "total": 57,
        "qtddiasgain": 83,
        "dadosanalisados": 5058,
        "id": "DhyQfcuu6oFBSlUXaNH6",
        "src": "BOV_SANB3.png",
        "name": "SANB3",
        "gainporcentagem": "47.37",
        "lossporcentagem": "52.63",
        "profit": 2060,
        "score": "60.36",
        "condicao": "SINAL DE COMPRA:Bollinger=>Preço cruza para baixo da lowerband:desvio=2,periodo=20   SINAL DE VENDA:Saída=>Saida após (n) periodos:periodo=1   "
    },
    {
        "dadosanalisados": 5064,
        "qtdgain": 51,
        "gain": 3.41,
        "qtddiasgain": 75,
        "qtdloss": 66,
        "payoff": 2.05,
        "total": 117,
        "loss": -1.66,
        "qtddiasloss": 91,
        "nickname": "Pedro Hugo",
        "profitporcentagem": "18.12",
        "maximumdrawndown": -22.91,
        "id": "FAAlnMtTs2zeeRcRiNfl",
        "src": "BOV_ITSA4.png",
        "name": "ITSA4",
        "gainporcentagem": "43.59",
        "lossporcentagem": "56.41",
        "profit": 1180,
        "score": "43.05",
        "condicao": "SINAL DE COMPRA:Bollinger=>Preço acima upperband:desvio=2,periodo=20   SINAL DE VENDA:Média=>Preço maior que média :S. média=20,   "
    },
    {
        "total": 1403,
        "qtdloss": 673,
        "qtddiasgain": 1299,
        "qtddiasloss": 2470,
        "qtdgain": 730,
        "loss": -112.36,
        "dadosanalisados": 5064,
        "gain": 114.39,
        "payoff": 1.02,
        "nickname": "lucas",
        "maximumdrawndown": -35.53,
        "profitporcentagem": "203.10",
        "id": "Ht4KYAUtxSdatU7B5vF3",
        "src": "BOV_BBDC4.png",
        "name": "BBDC4",
        "gainporcentagem": "52.03",
        "lossporcentagem": "47.97",
        "profit": 3030,
        "score": "54.36",
        "condicao": "SINAL DE COMPRA:Média=>Preço maior que média :S. média=20,   SINAL DE VENDA:Média=>Preço maior que média :S. média=20,   "
    },
    {
        "qtddiasgain": 58,
        "nickname": "pedro",
        "qtdloss": 22,
        "maximumdrawndown": -13.9,
        "gain": 27.06,
        "total": 47,
        "profitporcentagem": "32.46",
        "qtdgain": 25,
        "payoff": 1.82,
        "loss": -14.88,
        "qtddiasloss": 58,
        "dadosanalisados": 5063,
        "id": "Ilfa5q4cAMaLp2eQcSwO",
        "src": "BOV_VALE3.png",
        "name": "VALE3",
        "gainporcentagem": "53.19",
        "lossporcentagem": "46.81",
        "profit": 1320,
        "score": "42.54",
        "condicao": "SINAL DE COMPRA:Bollinger=>Preço cruza para baixo da lowerband:desvio=2,periodo=20   SINAL DE VENDA:Saída=>Saida após (n) periodos:periodo=1   "
    },
    {
        "qtddiasgain": 3068,
        "payoff": 1.04,
        "profitporcentagem": "424.68",
        "qtddiasloss": 3135,
        "maximumdrawndown": -59.07,
        "gain": 113.48,
        "loss": -109.25,
        "qtdloss": 248,
        "total": 473,
        "qtdgain": 225,
        "nickname": "dani",
        "dadosanalisados": 5063,
        "id": "JfrUnjjESOwZkKDAOhgQ",
        "src": "BOV_CSNA3.png",
        "name": "CSNA3",
        "gainporcentagem": "47.57",
        "lossporcentagem": "52.43",
        "profit": 5250,
        "score": "50.14",
        "condicao": "SINAL DE COMPRA:Data=>A partir dessa Data:   SINAL DE VENDA:Data=>A partir dessa Data:   "
    },
    {
        "nickname": "pedro",
        "profitporcentagem": "32.46",
        "qtdgain": 25,
        "payoff": 1.82,
        "total": 47,
        "qtdloss": 22,
        "maximumdrawndown": -13.9,
        "dadosanalisados": 5063,
        "qtddiasgain": 58,
        "qtddiasloss": 58,
        "loss": -14.88,
        "gain": 27.06,
        "id": "JvBR2K0Y89aVVkh0ZPOf",
        "src": "BOV_VALE3.png",
        "name": "VALE3",
        "gainporcentagem": "53.19",
        "lossporcentagem": "46.81",
        "profit": 1320,
        "score": "42.54",
        "condicao": "SINAL DE COMPRA:Bollinger=>Preço cruza para baixo da lowerband:desvio=2,periodo=20   SINAL DE VENDA:Saída=>Saida após (n) periodos:periodo=1   "
    },
    {
        "qtdgain": 1215,
        "qtddiasgain": 1778,
        "maximumdrawndown": -28.5,
        "payoff": 1.04,
        "dadosanalisados": 5063,
        "nickname": "Lucas Martins",
        "qtddiasloss": 1957,
        "loss": -349.57,
        "qtdloss": 1315,
        "profitporcentagem": "309.75",
        "gain": 364.98,
        "total": 2530,
        "id": "KViPxfjACYRimMTUodis",
        "src": "BOV_BBAS3.png",
        "name": "BBAS3",
        "gainporcentagem": "48.02",
        "lossporcentagem": "51.98",
        "profit": 4100,
        "score": "58.27",
        "condicao": "SINAL DE COMPRA:Acumulação/Distribuição=>Acum/Dist sequência de alta:   SINAL DE VENDA:Acumulação/Distribuição=>Acum/Dist sequência de alta:   "
    },
    {
        "payoff": 1.05,
        "qtddiasloss": 2176,
        "gain": 70.8,
        "loss": -67.7,
        "maximumdrawndown": -31.78,
        "profitporcentagem": "169.17",
        "dadosanalisados": 5064,
        "qtddiasgain": 1542,
        "total": 2530,
        "qtdgain": 1069,
        "nickname": "Pedro Hugo",
        "qtdloss": 1461,
        "id": "LS0HVCAQeC8cnfpMsd9C",
        "src": "BOV_ITSA4.png",
        "name": "ITSA4",
        "gainporcentagem": "42.25",
        "lossporcentagem": "57.75",
        "profit": 2690,
        "score": "50.13",
        "condicao": "SINAL DE COMPRA:Acumulação/Distribuição=>Acum/Dist sequência de alta:   SINAL DE VENDA:Acumulação/Distribuição=>Acum/Dist sequência de alta:   "
    },
    {
        "qtdgain": 42,
        "qtddiasloss": 69,
        "qtddiasgain": 118,
        "gain": 9.17,
        "profitporcentagem": "83.98",
        "maximumdrawndown": -13.04,
        "loss": -3.73,
        "payoff": 2.46,
        "total": 65,
        "nickname": "pedro",
        "dadosanalisados": 5064,
        "qtdloss": 23,
        "id": "NSGxj0wRWc600Gqv1jWK",
        "src": "BOV_BBDC3.png",
        "name": "BBDC3",
        "gainporcentagem": "64.62",
        "lossporcentagem": "35.38",
        "profit": 1840,
        "score": "57.35",
        "condicao": "SINAL DE COMPRA:Bollinger=>Preço cruza para baixo da lowerband:desvio=2,periodo=20   SINAL DE VENDA:Saída=>Saida após (n) periodos:periodo=1   "
    },
    {
        "loss": -4.69,
        "maximumdrawndown": -12.94,
        "qtddiasloss": 151,
        "gain": 5.86,
        "qtdloss": 109,
        "profitporcentagem": "50.93",
        "total": 210,
        "qtddiasgain": 151,
        "dadosanalisados": 5064,
        "payoff": 1.25,
        "qtdgain": 101,
        "nickname": "Pedro Hugo",
        "id": "QZWMuQt8WC9h3veXRX2m",
        "src": "BOV_ITSA4.png",
        "name": "ITSA4",
        "gainporcentagem": "48.10",
        "lossporcentagem": "51.90",
        "profit": 1510,
        "score": "36.75",
        "condicao": "SINAL DE COMPRA:MACD=>Macd cruzou acima signal line:M. longa=26,M. rapida=12,periodo=>9,   SINAL DE VENDA:Candles=>Candle sequência de alta:seq=0   "
    },
    {
        "loss": -312.08,
        "total": 1557,
        "payoff": 1.14,
        "dadosanalisados": 5063,
        "gain": 355.57,
        "qtdloss": 704,
        "qtdgain": 853,
        "nickname": "pedro",
        "qtddiasgain": 1909,
        "qtddiasloss": 3236,
        "profitporcentagem": "298.98",
        "maximumdrawndown": -34.36,
        "id": "SQWA64ifyo29BR1fhq2Y",
        "src": "BOV_VALE3.png",
        "name": "VALE3",
        "gainporcentagem": "54.78",
        "lossporcentagem": "45.22",
        "profit": 3990,
        "score": "61.58",
        "condicao": "SINAL DE COMPRA:Acumulação/Distribuição=>Acum/Dist sequência de alta:   SINAL DE VENDA:Média Exponencial=>Preço maior que média exponencial:E. média=20,   "
    },
    {
        "gain": 53.9,
        "payoff": 0.94,
        "total": 291,
        "qtdloss": 209,
        "nickname": "pedro",
        "profitporcentagem": "83.81",
        "loss": -57.42,
        "qtdgain": 82,
        "qtddiasgain": 2890,
        "maximumdrawndown": -69.35,
        "dadosanalisados": 5064,
        "qtddiasloss": 1346,
        "id": "TbNwQgaisE8anB6Ue4oL",
        "src": "BOV_ITUB4.png",
        "name": "ITUB4",
        "gainporcentagem": "28.18",
        "lossporcentagem": "71.82",
        "profit": 1840,
        "score": "29.49",
        "condicao": "SINAL DE COMPRA:Média=>Preço cruzou pra cima da média:S. média=20,   SINAL DE VENDA:Média=>Preço cruzou pra baixo da média:S. média=20,   "
    },
    {
        "maximumdrawndown": -268.29,
        "qtddiasgain": 2600,
        "dadosanalisados": 5058,
        "qtddiasloss": 1915,
        "loss": -84.45,
        "nickname": "pedro",
        "gain": 36.09,
        "qtdgain": 50,
        "profitporcentagem": "-553.54",
        "payoff": 0.43,
        "qtdloss": 255,
        "total": 305,
        "id": "VT1p5ztoAYpeSqapUZMG",
        "src": "BOV_SANB3.png",
        "name": "SANB3",
        "gainporcentagem": "16.39",
        "lossporcentagem": "83.61",
        "profit": -4540,
        "score": "-12.50",
        "condicao": "SINAL DE COMPRA:Média=>Preço cruzou pra cima da média:S. média=20,   SINAL DE VENDA:Média=>Preço cruzou pra baixo da média:S. média=20,   "
    },
    {
        "qtddiasloss": 1915,
        "total": 305,
        "nickname": "pedro",
        "profitporcentagem": "-553.54",
        "payoff": 0.43,
        "dadosanalisados": 5058,
        "gain": 36.09,
        "qtddiasgain": 2600,
        "qtdloss": 255,
        "maximumdrawndown": -268.29,
        "loss": -84.45,
        "qtdgain": 50,
        "id": "WmH8nCBxMHcfi7YkEZqK",
        "src": "BOV_SANB3.png",
        "name": "SANB3",
        "gainporcentagem": "16.39",
        "lossporcentagem": "83.61",
        "profit": -4540,
        "score": "-12.50",
        "condicao": "SINAL DE COMPRA:Média=>Preço cruzou pra cima da média:S. média=20,   SINAL DE VENDA:Média=>Preço cruzou pra baixo da média:S. média=20,   "
    },
    {
        "nickname": "pedro",
        "dadosanalisados": 5058,
        "total": 305,
        "gain": 36.09,
        "maximumdrawndown": -268.29,
        "payoff": 0.43,
        "qtdgain": 50,
        "qtddiasgain": 2600,
        "qtddiasloss": 1915,
        "loss": -84.45,
        "profitporcentagem": "-553.54",
        "qtdloss": 255,
        "id": "XUVDvhF8Vo9ILr9hLL9M",
        "src": "BOV_SANB3.png",
        "name": "SANB3",
        "gainporcentagem": "16.39",
        "lossporcentagem": "83.61",
        "profit": -4540,
        "score": "-12.50",
        "condicao": "SINAL DE COMPRA:Média=>Preço cruzou pra cima da média:S. média=20,   SINAL DE VENDA:Média=>Preço cruzou pra baixo da média:S. média=20,   "
    },
    {
        "profitporcentagem": "140.51",
        "qtddiasloss": 2524,
        "qtdgain": 720,
        "maximumdrawndown": -46.98,
        "loss": -197.44,
        "gain": 186.98,
        "qtddiasgain": 1272,
        "qtdloss": 687,
        "payoff": 0.95,
        "dadosanalisados": 5063,
        "total": 1407,
        "nickname": "Lucas",
        "id": "aH9hz31lP8rmgJwW7yAp",
        "src": "BOV_BBAS3.png",
        "name": "BBAS3",
        "gainporcentagem": "51.17",
        "lossporcentagem": "48.83",
        "profit": 2410,
        "score": "50.04",
        "condicao": "SINAL DE COMPRA:Média=>Preço maior que média :S. média=20,   SINAL DE VENDA:Média=>Preço maior que média :S. média=20,   "
    },
    {
        "dadosanalisados": 5065,
        "payoff": 1.16,
        "qtdloss": 112,
        "maximumdrawndown": -42.42,
        "nickname": "pedro",
        "loss": -23.2,
        "gain": 26.88,
        "qtddiasgain": 1014,
        "qtddiasloss": 1140,
        "profitporcentagem": "125.18",
        "total": 295,
        "qtdgain": 183,
        "id": "aLe5KwrwwdlevCxA73wI",
        "src": "BOV_ABEV3.png",
        "name": "ABEV3",
        "gainporcentagem": "62.03",
        "lossporcentagem": "37.97",
        "profit": 2250,
        "score": "44.70",
        "condicao": "SINAL DE COMPRA:Média=>Preço cruzou pra cima da média:S. média=10,   SINAL DE VENDA:MACD=>Macd acima de zero:M. longa=26,M. rapida=12,periodo=>10,   "
    },
    {
        "profitporcentagem": "254.92",
        "total": 309,
        "qtdgain": 225,
        "loss": -14.95,
        "maximumdrawndown": -25.39,
        "nickname": "Ifr2",
        "dadosanalisados": 3512,
        "gain": 31.3,
        "qtddiasgain": 796,
        "qtdloss": 84,
        "qtddiasloss": 750,
        "payoff": 2.09,
        "id": "aP7ZKJgsYkviJhwMxkt5",
        "src": "BOV_EQTL3.png",
        "name": "EQTL3",
        "gainporcentagem": "72.82",
        "lossporcentagem": "27.18",
        "profit": 3550,
        "score": "69.06",
        "condicao": "SINAL DE COMPRA:IFR=>Entrou na zona de sobrevenda:sobrecomprado=80,sobrevendido=25,periodo=2,   SINAL DE VENDA:Média=>Preço maior que média :S. média=5,   "
    },
    {
        "maximumdrawndown": -53.56,
        "dadosanalisados": 5064,
        "payoff": 1.59,
        "qtddiasloss": 1216,
        "qtddiasgain": 2893,
        "loss": -37.96,
        "qtdloss": 193,
        "profitporcentagem": "285.75",
        "total": 270,
        "qtdgain": 77,
        "nickname": "pedro",
        "gain": 60.3,
        "id": "c8jNYzx5XS5BHyklpDpy",
        "src": "BOV_BBDC3.png",
        "name": "BBDC3",
        "gainporcentagem": "28.52",
        "lossporcentagem": "71.48",
        "profit": 3860,
        "score": "48.04",
        "condicao": "SINAL DE COMPRA:Média=>Preço cruzou pra cima da média:S. média=20,   SINAL DE VENDA:Média=>Preço cruzou pra baixo da média:S. média=20,   "
    },
    {
        "gain": 98.64,
        "nickname": "lucas",
        "dadosanalisados": 5064,
        "qtddiasloss": 2029,
        "qtdgain": 717,
        "loss": -93.83,
        "total": 1389,
        "qtddiasgain": 1271,
        "maximumdrawndown": -45.34,
        "payoff": 1.05,
        "qtdloss": 672,
        "profitporcentagem": "228.60",
        "id": "eG2twDd1MCMMjuIYNVj2",
        "src": "BOV_BBDC3.png",
        "name": "BBDC3",
        "gainporcentagem": "51.62",
        "lossporcentagem": "48.38",
        "profit": 3290,
        "score": "55.92",
        "condicao": "SINAL DE COMPRA:Média=>Preço maior que média :S. média=20,   SINAL DE VENDA:Média=>Preço maior que média :S. média=20,   "
    },
    {
        "total": 403,
        "profitporcentagem": "78.74",
        "qtdloss": 211,
        "maximumdrawndown": -20.44,
        "qtddiasgain": 315,
        "payoff": 0.87,
        "dadosanalisados": 5062,
        "qtdgain": 192,
        "nickname": "Lucas",
        "loss": -29.58,
        "qtddiasloss": 551,
        "gain": 25.85,
        "id": "gArO18a8PoKJi2cNa0uy",
        "src": "BOV_ALPA4.png",
        "name": "ALPA4",
        "gainporcentagem": "47.64",
        "lossporcentagem": "52.36",
        "profit": 1790,
        "score": "35.80",
        "condicao": "SINAL DE COMPRA:IFR=>Entrou na zona de sobrecompra:sobrecomprado=80,sobrevendido=20,periodo=2,   SINAL DE VENDA:Média=>Preço maior que média :S. média=5,   "
    },
    {
        "qtdloss": 254,
        "qtddiasgain": 440,
        "payoff": 1.16,
        "total": 543,
        "gain": 79.85,
        "qtddiasloss": 740,
        "nickname": "Lucas",
        "dadosanalisados": 5063,
        "maximumdrawndown": -29.54,
        "qtdgain": 289,
        "loss": -68.9,
        "profitporcentagem": "100.49",
        "id": "gRpD1ApKlKlHOLdDj3Bb",
        "src": "BOV_BBAS3.png",
        "name": "BBAS3",
        "gainporcentagem": "53.22",
        "lossporcentagem": "46.78",
        "profit": 2000,
        "score": "44.50",
        "condicao": "SINAL DE COMPRA:IFR=>Entrou na zona de sobrecompra:sobrecomprado=80,sobrevendido=25,periodo=2,   SINAL DE VENDA:Média=>Preço maior que média :S. média=5,   "
    },
    {
        "maximumdrawndown": -16.84,
        "qtddiasgain": 104,
        "qtdgain": 25,
        "total": 46,
        "profitporcentagem": "34.42",
        "gain": 27.93,
        "dadosanalisados": 5063,
        "payoff": 1.29,
        "qtdloss": 21,
        "loss": -21.73,
        "qtddiasloss": 85,
        "nickname": "pedro",
        "id": "gf3vU75HPFzAA8MkjENL",
        "src": "BOV_VALE3.png",
        "name": "VALE3",
        "gainporcentagem": "54.35",
        "lossporcentagem": "45.65",
        "profit": 1340,
        "score": "35.91",
        "condicao": "SINAL DE COMPRA:Bollinger=>Preço cruza para baixo da lowerband:desvio=2,periodo=20   SINAL DE VENDA:Saída=>Saida após (n) periodos:periodo=2   "
    },
    {
        "maximumdrawndown": -22.65,
        "payoff": 1.86,
        "qtdgain": 89,
        "qtddiasgain": 4042,
        "qtdloss": 28,
        "gain": 18.02,
        "loss": -9.67,
        "profitporcentagem": "408.44",
        "dadosanalisados": 5064,
        "qtddiasloss": 3207,
        "total": 117,
        "nickname": "Pedro Hugo",
        "id": "iOJJXeOoTLXGRxrlMspP",
        "src": "BOV_ITSA4.png",
        "name": "ITSA4",
        "gainporcentagem": "76.07",
        "lossporcentagem": "23.93",
        "profit": 5080,
        "score": "64.35",
        "condicao": "SINAL DE COMPRA:Média=>Preço maior que média :S. média=20,   SINAL DE VENDA:Bollinger=>Preço acima upperband:desvio=2,periodo=20   "
    },
    {
        "total": 154,
        "payoff": 0.99,
        "maximumdrawndown": -67.59,
        "qtdloss": 115,
        "qtddiasloss": 793,
        "profitporcentagem": "-7.32",
        "dadosanalisados": 3160,
        "gain": 35.85,
        "loss": -36.36,
        "qtdgain": 39,
        "qtddiasgain": 1501,
        "nickname": "pedro",
        "id": "lhgX8kp9pwrP6KFGALwu",
        "src": "BOV_BRSR6.png",
        "name": "BRSR6",
        "gainporcentagem": "25.32",
        "lossporcentagem": "74.68",
        "profit": 930,
        "score": "24.09",
        "condicao": "SINAL DE COMPRA:Média=>Preço cruzou pra cima da média:S. média=20,   SINAL DE VENDA:Média=>Preço cruzou pra baixo da média:S. média=20,   "
    },
    {
        "loss": -59.55,
        "qtddiasgain": 3743,
        "qtdloss": 21,
        "qtdgain": 104,
        "dadosanalisados": 5063,
        "total": 125,
        "qtddiasloss": 3452,
        "maximumdrawndown": -75.13,
        "gain": 62.23,
        "nickname": "Pedro",
        "payoff": 1.05,
        "profitporcentagem": "500.64",
        "id": "lxDAyB6Kqi3sIzjfg3PK",
        "src": "BOV_CSNA3.png",
        "name": "CSNA3",
        "gainporcentagem": "83.20",
        "lossporcentagem": "16.80",
        "profit": 6010,
        "score": "55.81",
        "condicao": "SINAL DE COMPRA:Média=>Preço maior que média :S. média=20,   SINAL DE VENDA:Bollinger=>Preço acima upperband:desvio=2,periodo=20   "
    },
    {
        "profitporcentagem": "421.24",
        "maximumdrawndown": -44.66,
        "nickname": "pedro",
        "payoff": 1.7,
        "qtdgain": 75,
        "gain": 116.12,
        "loss": -68.19,
        "total": 262,
        "qtdloss": 187,
        "qtddiasgain": 3044,
        "dadosanalisados": 5063,
        "qtddiasloss": 1120,
        "id": "pEKVrzLD5G6eyWezdREc",
        "src": "BOV_BBAS3.png",
        "name": "BBAS3",
        "gainporcentagem": "28.63",
        "lossporcentagem": "71.37",
        "profit": 5210,
        "score": "50.14",
        "condicao": "SINAL DE COMPRA:Média=>Preço cruzou pra cima da média:S. média=20,   SINAL DE VENDA:Média=>Preço cruzou pra baixo da média:S. média=20,   "
    },
    {
        "qtddiasgain": 114,
        "loss": -6.43,
        "qtddiasloss": 48,
        "maximumdrawndown": -7.21,
        "nickname": "pedro",
        "qtdloss": 17,
        "payoff": 1.1,
        "total": 54,
        "qtdgain": 37,
        "gain": 7.06,
        "profitporcentagem": "47.51",
        "dadosanalisados": 5064,
        "id": "pvnTvMithH73JtmkQ5XJ",
        "src": "BOV_ITUB4.png",
        "name": "ITUB4",
        "gainporcentagem": "68.52",
        "lossporcentagem": "31.48",
        "profit": 1480,
        "score": "38.40",
        "condicao": "SINAL DE COMPRA:Bollinger=>Preço cruza para baixo da lowerband:desvio=2,periodo=20   SINAL DE VENDA:Saída=>Saida após (n) periodos:periodo=1   "
    },
    {
        "dadosanalisados": 5062,
        "nickname": "Lucas Martins",
        "payoff": 1.21,
        "qtddiasgain": 1899,
        "qtdloss": 834,
        "total": 1541,
        "profitporcentagem": "506.73",
        "qtdgain": 707,
        "gain": 82.18,
        "maximumdrawndown": -64.8,
        "loss": -68.06,
        "qtddiasloss": 3265,
        "id": "rd2uE2CyfFrzL0e8mzjo",
        "src": "BOV_ALPA4.png",
        "name": "ALPA4",
        "gainporcentagem": "45.88",
        "lossporcentagem": "54.12",
        "profit": 6070,
        "score": "59.90",
        "condicao": "SINAL DE COMPRA:Acumulação/Distribuição=>Acum/Dist sequência de alta:   SINAL DE VENDA:Média=>Preço maior que média :S. média=20,   "
    },
    {
        "qtdloss": 29,
        "qtdgain": 32,
        "qtddiasloss": 78,
        "payoff": 1.43,
        "loss": -15.63,
        "gain": 22.3,
        "profitporcentagem": "28.46",
        "maximumdrawndown": -20.45,
        "dadosanalisados": 5063,
        "total": 61,
        "nickname": "pedro",
        "qtddiasgain": 83,
        "id": "rs1unPRfcOmaGkudJDSY",
        "src": "BOV_BBAS3.png",
        "name": "BBAS3",
        "gainporcentagem": "52.46",
        "lossporcentagem": "47.54",
        "profit": 1280,
        "score": "37.13",
        "condicao": "SINAL DE COMPRA:Bollinger=>Preço cruza para baixo da lowerband:desvio=2,periodo=20   SINAL DE VENDA:Saída=>Saida após (n) periodos:periodo=1   "
    },
    {
        "qtdgain": 6,
        "nickname": "pedro",
        "total": 20,
        "dadosanalisados": 521,
        "qtddiasloss": 128,
        "payoff": 2.54,
        "qtddiasgain": 276,
        "maximumdrawndown": -9.52,
        "profitporcentagem": "225.12",
        "loss": -7.13,
        "qtdloss": 14,
        "gain": 18.09,
        "id": "xZMjreTQkCRaBfT3jIIj",
        "src": "BOV_BIDI4.png",
        "name": "BIDI4",
        "gainporcentagem": "30.00",
        "lossporcentagem": "70.00",
        "profit": 3250,
        "score": "57.00",
        "condicao": "SINAL DE COMPRA:Média=>Preço cruzou pra cima da média:S. média=20,   SINAL DE VENDA:Média=>Preço cruzou pra baixo da média:S. média=20,   "
    },
    {
        "qtddiasgain": 71,
        "qtdgain": 27,
        "payoff": 2.44,
        "maximumdrawndown": -8.7,
        "profitporcentagem": "50.48",
        "loss": -4.34,
        "gain": 10.61,
        "qtdloss": 18,
        "dadosanalisados": 3160,
        "total": 45,
        "nickname": "pedro",
        "qtddiasloss": 52,
        "id": "y4K7KfijXZ4BM7pyfqlo",
        "src": "BOV_BRSR6.png",
        "name": "BRSR6",
        "gainporcentagem": "60.00",
        "lossporcentagem": "40.00",
        "profit": 1500,
        "score": "54.13",
        "condicao": "SINAL DE COMPRA:Bollinger=>Preço cruza para baixo da lowerband:desvio=2,periodo=20   SINAL DE VENDA:Saída=>Saida após (n) periodos:periodo=1   "
    }
];


export default data